version: '3'

services:

  database:
    image: postgres:15.4
    volumes:
      - ./src/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: Oversight
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    ports:
      - "5432:5432"
    networks:
      - compose-network
    expose:
      - 5432

  rabbitmq:
    build:
      context: .
      dockerfile: ./src/rabbitMQ/Dockerfile
    container_name: messenger
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - compose-network
    restart: always

  backend:
    build: ./src/backend
    ports:
      - 3001:3001
    volumes:
      - './src/backend:/app:cached'
      - '/app/node_modules'
    restart: always
    environment:
      - API_PORT=3001
      - DB_USER=postgres
      - DB_PASS=toor
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=Oversight
      - KEY=jAhm*uq+c@esxi4+qimte&x
      - AUTH=qimte&x+c@esxi4+pQhm*uq
      - ENV=dev
    expose:
      - 3001
    depends_on:
      - database
    networks:
      - compose-network

  messenger:
    build: ./src/messenger
    ports:
      - 3002:3002
    volumes:
      - './src/messenger:/app:cached'
      - '/app/node_modules'
    restart: always
    environment:
      - API_PORT=3002
      - DB_USER=postgres
      - DB_PASS=toor
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=Oversight
      - KEY=jAhm*uq+c@esxi4+qimte&x
      - AUTH=qimte&x+c@esxi4+pQhm*uq
      - ENV=dev
      - AMQP_USER=john123
      - AMQP_PASS=123456
      - AMQP_HOST=rabbitmq:5672
    expose:
      - 3002
    depends_on:
      - database
      - rabbitmq
    networks:
      - compose-network

  gateway:
    build: ./src/gateway
    ports:
      - 3000:3000
    volumes:
      - './src/gateway:/app:cached'
      - '/app/node_modules'
    restart: always
    environment:
      - GATEWAY_PORT=3000
      - DB_USER=postgres
      - DB_PASS=toor
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=Oversight
      - KEY=jAhm*uq+c@esxi4+qimte&x
      - AUTH=qimte&x+c@esxi4+pQhm*uq
      - API_URL=http://backend:3001
      - MESSENGER_URL=http://messenger:3002
      - ENV=dev
    networks:
      - compose-network
    depends_on:
      - backend
      - messenger
    expose:
      - 3000

  frontend:
    build: ./src/front_web
    ports:
      - 80:80
    volumes:
      - './src/front_web:/app:cached'
      - '/app/oversight/node_modules'
    restart: always
    environment:
      - PORT=80
      - ENV=dev #change to prod on deploy
      - DISABLE_ESLINT_PLUGIN=true
      - NEXT_PUBLIC_API_ENDPOINT=http://0.0.0.0:3000
    expose:
      - 80
    networks:
      - compose-network
    depends_on:
      - gateway
      - backend
      - messenger

networks:
  compose-network:
    driver: bridge

volumes:
  logs-folder:
    name: ${log_rabbitmq_management}
    driver: local
