name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: cd codigo && docker compose up -d && sleep 30
    - name: Test
      run: docker exec -i $(docker ps -f name=codigo-gateway -q) npm run test
